GET http://localhost:5001/exercises
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImRpc3BsYXlfbmFtZSI6IkNhbGViIiwiZW1haWwiOiJjYWxlYkBleGFtcGxlLmNvbSIsImlkIjoiNmFiYTBkMGQ5MTM2MWFiNmMyZGE5OTQxIn0sImlhdCI6MTc5MDU4NzgzOCwiZXhwIjoxNzkwNTg4NzM4fQ.Uxa_vLh19erncsITgycNQSnu3JN02x7ugYI8V8a8214
